# Что сегодня сделаем
Рекомендательный алгоритм сопутствующих товаров для пользователя

### Повторим списки и словари
Статистика взята с сайта http://www.bodycounters.com

Дана статистика погибших в серии фильмов "Пираты Карибского моря". Посчитайте среднее число погибших людей в каждом фильме. Пиратов зомби за людей не считайте.

In [6]:
stats = [
    {
        'movie': 'На странных берегах',
        'bodycount': {'люди': 56, 'русалки': 2, 'ядовитые жабы': 3, 'пираты-зомби': 2}
    },
    {
        'movie': 'На краю света',
        'bodycount': {'люди': 88}
    },
    {
        'movie': 'Сундук мертвеца',
        'bodycount': {'люди': 56, 'крабы отшельники': 1}
    },
    {
        'movie': 'Проклятие Черной жемчужины',
        'bodycount': {'люди': 17}
    },
]

Что можно сделать:
1. Пройтись по списку stats
2. В каждом элементе взять словарь по ключу 'bodycount'
3. В словаре по ключу 'bodycount' взять значение ключа 'люди'
4. Просуммировать количество людей во всех шагах
5. Поделить сумму людей на количество фильмов

In [18]:
z = 0
numofelem = 0
for elem in stats:
    x = {}
    x = elem.get('bodycount')
    z += int(x.get('люди'))
    numofelem += 1
print(z / numofelem)

54.25


# Numpy и матричная алгебра

In [7]:
import numpy as np

In [24]:
x = np.array([1, 2, 3])
y = np.array( [4, 5, 6] )

In [ ]:
# у переменной x тип, отличный от list
type(x)

In [3]:
# дополнительные методы
?np.mean()

Object `np.mean()` not found.


### Поэлементные операции

In [ ]:
x + y

In [ ]:
x - y

In [ ]:
x * y

In [ ]:
x / y

In [ ]:
# элементы массива x возводятся в соответствующие степени элементов массива y
x ** y

In [ ]:
# остаток от деления
# обратите внимание, что для удобства данного примера x и y идут в другом порядке

y % x

### Автоматическое наполнение массивов

In [26]:
# аналог range

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# создать массив из 10 чисел, заполненных единицами
np.full(10, 1)

In [ ]:
# создать матрицу 2х5 из нулей
np.full([2, 5], 0)

In [ ]:
# объединить массивы в один
a = np.arange(10)
b = np.arange(10, 20)

# обратите внимание на двойные скобки
np.concatenate((a, b))

In [27]:
# перемешать элементы массива
import random

nums = np.arange(10)
random.shuffle(nums)

nums

array([1, 5, 0, 7, 2, 3, 9, 4, 6, 8])

### Упражнение
По мотивам https://thecode.media/choose-life/

По результатам собеседования вам предлагают определенную зарплату. И конверт, который может случайным образом снизить или увеличить эту зарплату вдвое. Т. е. если сначала была сумма Х, то после вскрытия конверта она может стать 0.5Х или 2Х. Как в среднем изменится будущая зарплата, если соискатель решил открыть конверт?

Смоделируйте процесс изменения условной зарплаты в 1000 в случае открытия конверта:
1. Задайте переменную n_samples = 1000
2. Создайте numpy array из n_samples элементов, равных зарплате 0.5Х. И такой же с зарплатой 2Х.
3. Объедините их в один массив
4. Перемешайте значения в получившемся массиве
5. Посчитайте среднее значение зарплаты для объединенного массива

In [30]:
n_s = 1000
x = np.full(n_s, 500)
z = np.full(n_s, 2000)
y = np.concatenate((x, z))
random.shuffle(y)
np.mean(y)

1250.0

### Изменение размерности

In [8]:
x = np.arange( 0, 10 )
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 10 - количество строк

x.shape

(10,)

In [10]:
# первый аргумент - количество строк
# второй - столбцов

x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
x.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [ ]:
# транспонирование матриц

np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
).T

In [ ]:
# склеивание набора списков
[1, 2, 3] + [4, 5, 6]

In [ ]:
# склеивание массива из списков

x = np.array( [ [1, 2, 3], [4, 5, 6] ] )
x.ravel()

In [ ]:
# можно и так

x.reshape(6)

In [ ]:
# результат разный, если добавить 1 в качестве количества строк

x.reshape(1, 6)

### Создание матриц

In [ ]:
# нулевой вектор заданной размерности

np.zeros(10)

In [33]:
# единичная матрица

np.eye(5, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# более общий случай диагональной матрицы

np.diag(np.arange(2, 50, 15), k=0)

array([[ 2,  0,  0,  0],
       [ 0, 17,  0,  0],
       [ 0,  0, 32,  0],
       [ 0,  0,  0, 47]])

In [37]:
# матрица со случайными значениями

np.random.random(1)

array([4.78442691e-01, 1.19552378e-01, 5.99364107e-01, 6.17867707e-01,
       8.66945804e-01, 3.41278971e-01, 6.09698885e-01, 8.49414972e-01,
       6.64551639e-01, 1.68792397e-01, 9.55209649e-01, 2.15728511e-01,
       7.93821960e-01, 1.18822148e-01, 7.02626764e-01, 2.01181689e-04,
       8.43842606e-01, 8.93871627e-01, 7.87958543e-01, 7.41433874e-01,
       3.18651783e-01, 1.93599523e-01, 6.50147254e-01, 3.68706841e-01,
       3.44653403e-01])

In [39]:
# более универсальный вариант создания матриц

?np.linspace

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [38]:
np.linspace(5, 25, 30)

array([ 5.        ,  5.68965517,  6.37931034,  7.06896552,  7.75862069,
        8.44827586,  9.13793103,  9.82758621, 10.51724138, 11.20689655,
       11.89655172, 12.5862069 , 13.27586207, 13.96551724, 14.65517241,
       15.34482759, 16.03448276, 16.72413793, 17.4137931 , 18.10344828,
       18.79310345, 19.48275862, 20.17241379, 20.86206897, 21.55172414,
       22.24137931, 22.93103448, 23.62068966, 24.31034483, 25.        ])

### Более сложные распределения

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.gaussian.html

### Упражнение
Дана единичная матрица np.eye(10). Посчитайте сумму ее диагональных элементов.

In [41]:
x = np.eye(10)
summa = 0
z = 0
for elem in x:
    summa += elem[z]
    z += 1
print(summa) 

10.0


# Скалярное произведение векторов

\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = |\vec{a}| \space |\vec{b}| \space cos(\vec{a}, \vec{b})
\end{equation*}

Пусть 
\begin{equation*}
\LARGE
\vec{a} = (a_1, a_2, a_3) \\
\LARGE
\vec{b} = (b_1, b_2, b_3)
\end{equation*}

Тогда скалярное произведение векторов равно
\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = a_1 b_1 + a_2 b_2 + a_3 b_3
\end{equation*}

In [52]:
a = np.array( [4, 3] )
b = np.array( [2, 1] )


array([16,  9])

Пример расчета скалярного произведения векторов

In [50]:
np.dot( a, b )

11

Можно посчитать и таким образом

In [ ]:
# первый шаг

for pair in zip( a, b ):
    print( pair )

In [ ]:
# второй шаг

[ pair[0] * pair[1] for pair in zip( a, b ) ]

In [ ]:
# итоговый результат

sum( [ pair[0] * pair[1] for pair in zip( a, b ) ] )

# Косинусное расстояние между векторами

\begin{equation*}
\LARGE
cos(\vec{a}, \vec{b}) = \frac{\vec{a} \dot{} \vec{b}}{|\vec{a}| \space |\vec{b}|}
\end{equation*}

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
ax = plt.axes()

plt.xlim( [0, 5] )
plt.ylim( [0, 4] )

ax.arrow( 0, 0, a[0], a[1], head_width=0.1, head_length=0.2, fc='k', ec='k' )
ax.arrow( 0, 0, b[0], b[1], head_width=0.1, head_length=0.2, fc='k', ec='k' )

plt.show()

In [51]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [ ]:
# длины векторов можно было посчитать и так

aLength = np.sqrt( (a*a).sum() )
bLength = np.sqrt( (b*b).sum() )

In [ ]:
cosine( a, b )

In [ ]:
# угол между векторами в радианах

np.arccos( cosine( a, b ) )

In [ ]:
# угол между векторами в градусах

np.arccos( cosine( a, b ) ) * 360 / 2 / np.pi

## Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

[ 7 11  9  3 13 15 23 19 21  5  1 17]


Матрица в виде numpy array

In [37]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [41]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [53]:
def cos_angle(x, y):
    print(x.sum())
    print(y.sum())
    print(np.dot(x, y))
    print(np.sqrt(x.sum()* x.sum()))
    return(np.dot(x, y) / (np.sqrt((x * x).sum()) * np.sqrt((y * y).sum())))


for elem in users_stats:
    print(cos_angle(elem, next_user_stats))

3
3
1
3.0
0.19999999999999996
5
3
5
5.0
0.8451542547285165
3
3
2
3.0
0.3999999999999999
6
3
5
6.0
0.7905694150420948
3
3
2
3.0
0.3999999999999999
5
3
0
5.0
0.0
1
3
0
1.0
0.0
2
3
3
2.0
0.9486832980505138
5
3
0
5.0
0.0
8
3
0
8.0
0.0


# Перемножение матриц

**Определение**

Пусть даны две матрицы a и b размером l x m и m x n соответственно. l - количество строк, n - количество столбцов.

\begin{equation*}
\LARGE
a = 
\begin{bmatrix}
    a_{11} & a_{12} \dots a_{1m} \\
    a_{21} & a_{22} \dots a_{2m} \\
    \vdots & \vdots \dots \vdots \\
    a_{l1} & a_{l2} \dots a_{lm}
\end{bmatrix}
\end{equation*}

<br>

\begin{equation*}
\LARGE
b = 
\begin{bmatrix}
    b_{11} & b_{12} \dots b_{1n} \\
    b_{21} & b_{22} \dots b_{2n} \\
    \vdots & \vdots \dots \vdots \\
    b_{m1} & b_{m2} \dots b_{mn}
\end{bmatrix}
\end{equation*}

Тогда произведением матриц a и b будет матрица c размерностью l x n:

\begin{equation*}
\LARGE
c = 
\begin{bmatrix}
    c_{11} & c_{12} \dots c_{1n} \\
    c_{21} & c_{22} \dots c_{2n} \\
    \vdots & \vdots \dots \vdots \\
    c_{l1} & c_{l2} \dots c_{ln}
\end{bmatrix}
\end{equation*}

<br>

\begin{equation*}
\LARGE
c_{ij} = \sum_{k=1}^m a_{ik} b_{kj}
\end{equation*}

<img src = 'https://wikimedia.org/api/rest_v1/media/math/render/svg/1f96c71f0a99eac3ee872e7baf22e84324d7b4c9' style="width: 80%"></img>

In [ ]:
a = np.array( 
    [
        [1, 2],
        [3, 4]
    ] 
)

In [ ]:
b = np.array( 
    [
        [5, 6],
        [7, 8]
    ] 
)

In [ ]:
c = np.dot( a, b )
c

В numpy есть специальный тип matrix, который отличается от ndarray

In [ ]:
aMatrix = np.matrix( [ [1, 2], [3, 4] ] )
bMatrix = np.matrix( [ [5, 6], [7, 8] ] )

In [ ]:
type(aMatrix)

In [ ]:
aMatrix * bMatrix

In [ ]:
type( aMatrix ), type( a )

In [ ]:
np.mat( a ) * np.mat( b )

# Линейные уравнения

Дана система линейных уравнений

\begin{equation*}
\LARGE
x + 3*y = 9 \\
\LARGE
2*x - 4*y = 8
\end{equation*}

In [34]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [1, 3], [2, -4] ] )

In [33]:
# значения в правой части уравнения

b = np.array( [9, 8] )

In [ ]:
# решение

from numpy import linalg

In [35]:
linalg.solve(a, b)

array([6., 1.])

In [ ]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )


Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [36]:
from numpy import linalg
a = np.array( [[4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array([4, 12, -3])

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])