In [11]:
# Создать вектор или массив из 0, заданной размерности 
import numpy as np
#матрица
x = np.full([3, 3], 9)
print(x)

#вектор
y = np.full(10, 5)
print(y)

#Создать единичную матрицу из n числа элементов

nul = np.eye(3)
print(nul)


#Создать ед. матрицу со значениями на диагонали
list_1 = [1, 3, 4, 5, 6,]
zn = np.diag(list_1, k = 0)
print(zn)

#Создание массива со случайными значениями
import random

what = np.random.random(4)
print(what)

#Массив со равным промежутком между элементами диапазона
ret = np.linspace(1, 5, 20)
print(ret)

#


#


#

[[9 9 9]
 [9 9 9]
 [9 9 9]]
[5 5 5 5 5 5 5 5 5 5]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]
[0.05195446 0.32810194 0.52997545 0.24824766]
[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [17]:
# Сложение матриц и векторов

mat1 = np.full([len(list_1),len(list_1)], 0)
mat2 = np.diag(list_1, k = 0)

var1 = np.concatenate((mat1, mat2))

var3 = np.dot(mat1, mat2)


print(var1, var3)
print(mat2)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]] [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]


In [43]:
# Перемешать элементы массива
import random
tre = np.arange(1, 24, 2)
random.shuffle(tre)
print(tre)
ert = tre.reshape(3, 4)
#np.array(ert).T
print(ert)
#Определить количество строк и столбцов 

print(var1.shape)

[ 5 11 13 17  9 19  3  7 21 23 15  1]
[[ 5 11 13 17]
 [ 9 19  3  7]
 [21 23 15  1]]
(10, 5)
